### ISSUE TITLE
[hemera-zipkin] Dependency graph not showing edges

### ISSUE THREAD

**Issue by sberryman** [hemerajs/hemera#100]
> Hi @sberryman I think I found the issue. There is something wrong with the annotations which are send to zipkin. This can take a while but I will fix it. Could you open an issue?

Based on what I saw last night you have an almost identical copy of seneca-zipkin-tracer including the zipkin-simple package.

From zipkin-simple:
Annotation Data contains additional info about the current method:
- service: the name of the current service. It should be an identifier of running process (or class of processes), i.e.: web_server, background_worker, checkout_process. This will be displayed in the zipkin console
- name: the name of the method being tracked, i.e.: POST /user or update_credentials. Thi will be displayed in the zipking console on the single span

**Comment by StarpTech** [comment]
Fixed with hemera 1.3.3 and hemera-zipkin 1.0.11 
There are two tracking levels available. For more details look in the updated readme and example.

https://github.com/hemerajs/hemera/tree/master/packages/hemera-zipkin#tracking-level
