### ISSUE TITLE
when i'm kill the hemera app, but the hemera-web's port still has run.

### ISSUE THREAD

**Issue by arden** [hemerajs/hemera#111]
when i'm kill the hemera app, but the hemera-web's port still has run.

**Comment by StarpTech** [comment]
Hi @arden how you kill the service and which versions are you using?

**Comment by StarpTech** [comment]
I test it with the example `examples/bridges/web.js` and the server is closed correctly

```
[2017-07-08T09:08:23.655Z] FATAL (hemera-starptech-d325f33ea8cc4ca5a74a7c148f0bbad3/19600 on starptech): process exited
    code: null
    signal: "SIGINT"
[2017-07-08T09:08:23.656Z] DEBUG (hemera-starptech-d325f33ea8cc4ca5a74a7c148f0bbad3/19600 on starptech): Http server closed!
    plugin: "hemera-web"
```

**Comment by arden** [comment]
kill -9 <pid>
hemera 1.3.9

**Comment by StarpTech** [comment]
Which ouput do you get from hemera if you set logLevel to `debug` ?

**Comment by StarpTech** [comment]
After some research

> If no signal is specified, the TERM signal is sent.  The default
       action for this signal is to terminate the process.  This signal
       should be used in preference to the KILL signal (number 9), since a
       process may install a handler for the TERM signal in order to perform
       clean-up steps before terminating in an orderly fashion.  If a
       process does not terminate after a TERM signal has been sent, then
       the KILL signal may be used; be aware that the latter signal cannot
       be caught, and so does not give the target process the opportunity to
       perform any clean-up before terminating.

Please try kill without signal.
