### ISSUE TITLE
Allow setting store topic?

### ISSUE THREAD

**Issue by zhaoyao91** [hemerajs/hemera#121]
I notice that `mongo-store` topic is hard coding into the package. How about if I have multiple mongo stores in my services cluster?

**Comment by StarpTech** [comment]
I don't understand you question. `mongo-store` os only the name of the topic. If you have many instances of `mongo-store` the request is load balanced. What would you like to achieve?

**Comment by zhaoyao91** [comment]
> If you want to create a different mongo-store choose a different topic name. What would you like to achieve?

the problem is I can't change topic name if I use mongo-store package

**Comment by StarpTech** [comment]
@zhaoyao91 of course you can. `mongo-store` is a plugin to provide basic operations it shouldn't contains your business logic. It only provide you an easy interface to work with mongodb. if you want to create an order-service your topic would `order` or similiar and this service would call to `mongo-store` for example.

**Comment by StarpTech** [comment]
Closed,  due to inactivity.
