### ISSUE TITLE
How to integrate with Netflix Eureka?

### ISSUE THREAD

**Issue by danielsan** [hemerajs/hemera#140]
Hi everyone,

I'm trying to choose a microservices framework to use with node
but I really need to be able to integrate it with Eureka since we already have a
microservices infrastructure using Eureka :'(

Does anybody know how to use hemera with Eureka for service register/discovery?

**Comment by StarpTech** [comment]
Hi @danielsan there is no need for a service discovery because it's handled by NATS. Every microservice is a single subscription in NATS so you can save the complexity.

**Comment by danielsan** [comment]
Yeah, I know, that would be great if the company I work at was not already using Eureka.
We want to evolve our microservices platform by creating them in other languages (not only Java) and integrate them.

That is why I wanted to know how to make it work with Eureka, got it?

**Comment by StarpTech** [comment]
Then I don't understand the releation to hemera. In hemera you cant use a different service discovery it's built in. If you want to create a different driver in a different language you can easily communicate over NATS with the same protocol. There is already a java nats driver.

**Comment by StarpTech** [comment]
I also working on a client for Go https://github.com/hemerajs/go-hemera

**Comment by StarpTech** [comment]
@danielsan one of the primary tasks of nats is to provide load balancing and service discovery. It's based on the pub sub model so that  we can't provide modules for this. Please reopen if I couldn't answer your question.
