### ISSUE TITLE
Not returning error to api 

### ISSUE THREAD

**Issue by vforv** [hemerajs/hemera#149]
On api side where is hemera hapi I have basic act request:

```
createUser(req: HapiRequest, reply: Hapi.ReplyNoContinue) {
        let user: UserCreateInterface = req.payload;

        return req.hemera.act({ topic: 'user-save', type: 'amerbank', payload: user },
            function (err: any, result: any) {

                reply(err || result)
            })
    }
```

here is add in service:

```
this.hemera.add({
      topic: 'user-save',
      type: 'amerbank',
      email: Joi.number().required()
    }
```

In logs I get error messaga:

> [api - 7554]: 170908/201422.097, [error] message: child "email" fails because ["email" is required], stack: PreValidationError: child "email" fails because ["email" is required]
> [api - 7554]:     at Joi.validate (/home/master/Documents/trifecta/user-service/node_modules/hemera-joi/index.js:38:18)

But api returns:
Internal server error

**Comment by StarpTech** [comment]
This is the expected behaviour. If you return an error in hapi the default error code is 500. You can set it with `reply(err).code(400)` (404 bad request)

**Comment by StarpTech** [comment]
with the next release it's also possible to use `instanceof` to compare errors from plugins.

```js
const joiErrors = hemera.exposition['hemera-joi'].errors
if (err instanceof joiErrors.PreValidationError) {
             return reply({ success: false, message: err.message  }).code(404)
   } else {
        return reply(err)
}
```

**Comment by StarpTech** [comment]
In the next release it is possible to compare the errors with `instanceof` this is cleaner

**Comment by vforv** [comment]
Thanks, I make it works with boom.
