### ISSUE TITLE
Sometimes it works sometimes it doesn't

### ISSUE THREAD

**Issue by vforv** [hemerajs/hemera#153]
I am using mongodb atlas db to store data. When I use find query sometimes it pulls data sometimes it doesn't with the same query...

Here is code snippet:
```
public showUserByMail(msg: any, done: any): void {
        let __this: any = this;
        let hemera: T = __this;
        
        hemera.act({
            topic: 'mongo-store',
            cmd: 'find',
            collection: 'users',
            query: { email: msg.email }
        }, (err: Error, resp: any) => {
            if (err) {
                done(err);
            }
            console.log(resp)
            if(resp.result.length === 0) {
                done(null, false);
            } else {
                done(null, resp.result[0]);
            }
        })
    }
```

**Comment by StarpTech** [comment]
The code looks correct to me. Which output do you get in both cases?

**Comment by vforv** [comment]
When I start new service which also has `hemera-mongo-store` plugin problem occurs, sometimes it returns user data, and sometimes not a just empty array. I think problem is because both services creates same actions from `hemera-mongo-store` plugin.

**Comment by StarpTech** [comment]
That's not the problem because the request is load balanced. Could it be that one of the connection is wrong (different database etc...) ?

**Comment by vforv** [comment]
So both services should access to the same db?

**Comment by StarpTech** [comment]
Of course because they are addressed via the same topic.

**Comment by StarpTech** [comment]
Multi db support is not implemented but you can create a PR.

**Comment by vforv** [comment]
Oh, it is one of the keys features... :( It's very bad practice to have multiple connections to the same database, also there will be the problem if we decide to use the different database like sql dbs for different services...

**Comment by StarpTech** [comment]
> Oh, it is one of the keys features... :( It's very bad practice to have multiple connections to the same database, also there will be the problem if we decide to use the different database like sql dbs for different services...

What do you mean with this? If you use mongo-store you have one connection to the db. If you start mongo-db mulitple times you have n connections but any instance must point to the same db because the requests are load balanced.

**Comment by vforv** [comment]
Okay, but 2 different services have access to the same database... What if I decide to switch one service to work with mysql db because of transactions?

**Comment by StarpTech** [comment]
Then you would use two different drivers "mongo-store" and "sql-store"

**Comment by vforv** [comment]
Okay. Created pull request...

https://github.com/hemerajs/hemera/pull/154

**Comment by StarpTech** [comment]
Closed because the main issue was fixed.
