### ISSUE TITLE
Error on install

### ISSUE THREAD

**Issue by vitorcamachoo** [hemerajs/hemera#17]
During installation, this error occurs:
`
'flow-remove-types' is not recognized as an internal or external command,
operable program or batch file. 
`

I'm using:
- Windows 7
- Node 6.9.0

**Comment by StarpTech** [comment]
Hi @vitorcamachoo I will fix it but in the meanwhile you can try to install it globally and try it again. 

```
npm install - g flow-remove-types
```
Thanks!

**Comment by vitorcamachoo** [comment]
I just did:
- npm install nats-hemera -S -E

**Comment by StarpTech** [comment]
HI @vitorcamachoo issue was fixed with release `nats-hemera@0.3.1`

**Comment by vitorcamachoo** [comment]
Thanks for the fast reply.
