### ISSUE TITLE
Production ready??

### ISSUE THREAD

**Issue by skalyanapu-mtuity** [hemerajs/hemera#175]
Hi,

Firstly, I would like to thank you for your support to OS !!
To what extent Hemera was ready for enterprise-grade microservices architecture based applications, were user traffic would be 1000 - 1500 rps at peak time. Do you have any performance testing stats, of course, they are subjective to the type of computing operation you do, but any?

Does it have any circuit-breaking mechanism inbuilt ?? Is it scalable down the line, if required ??

Thank you !!

**Comment by StarpTech** [comment]
Hi @skalyanapu-mtuity thank you for checking out Hemera. Hemera is used by many companies (I know) https://github.com/hemerajs/hemera#whos-using-hemera

Hemera can handle on a single instance ~18K RPS but you are not limited. Hemera can be scaled infinitely. You need just start a separate instance of your service and everything else like (routing, load balancing, health check) is handled by the enterprise-ready messaging system NATS (the nervous system of Hemera)

Do you have any specific question?

> Does it have any circuit-breaking mechanism inbuilt ??

We had it before Hemera 2.0 but the implementation was not good enough. PR is very welcome!

Hemera can protect you by (builtin) https://github.com/hemerajs/hemera#built-in-protection

Some other characteristics which could influence your decision you can find here https://github.com/hemerajs/hemera#characteristics

I spent lots of time in the readme ;)

**Comment by skalyanapu-mtuity** [comment]
Hello @StarpTech,
Thank you for prompt suggestions. I came to know that "aither" was a bootstrap application  to start with developing microservices with "Hemera", also which(aither) includes robust deployment pipeline(sample) with integration with Docker, performance monitor also we found that there was Hapi dependency, does the knowledge of Hapi was mandatory to start working with Hamera, aren't we allowed to use other frameworks like express etc ..

Plugins:: Do we have the flexibility iof writing custom plugins which can be integrated wit Hamera , to meet custom requirements which are not covered by Hamera ??

For example , can we integrate 

Please provide your suggestions.

Thanks for your time :)

**Comment by StarpTech** [comment]
Hi @skalyanapu-mtuity Hemera has nothing in common with HTTP. Hapi serves as a API gateway to proxy HTTP Requests to Hemera. You can use any web framework of your choice but we provide plugins for Hapi and Fastify. The Hemera core should be small as possible. You can create as many plugins as you want.

**Comment by skalyanapu-mtuity** [comment]
OKay, thank you !!

Can we consider "aither" as an example project of the complete Hamera ecosystem from end to end ??

Regards,
Sai.

**Comment by StarpTech** [comment]
@skalyanapu-mtuity yes you can. It demonstrate the complete flow from Client (browser) to Service (Hemera)

**Comment by skalyanapu-mtuity** [comment]
Thank you !!
