### ISSUE TITLE
Module not found: Error: Can't resolve 'console'

### ISSUE THREAD

**Issue by veeramarni** [hemerajs/hemera#184]
I have noticed the plugin is requiring `console` but it is not listed in `dependencies` causing the following error.

https://github.com/hemerajs/hemera/blob/d8ce930d32e0d20f26a2a75a3b2f66fd2accb941/packages/hemera-plugin/index.js#L4

```
Module not found: Error: Can't resolve 'console' in '...node_modules/hemera-plugin'
```

**Comment by StarpTech** [comment]
Hi, which node version are you using?

**Comment by veeramarni** [comment]
I'm using v8, please see below. 

```
$ node -v
v8.8.1
$ npm -v
5.2.0
```

**Comment by StarpTech** [comment]
@veeramarni the module `console` is a core module https://nodejs.org/api/console.html

**Comment by veeramarni** [comment]
Ok thanks, looks like a problem with my build.
