### ISSUE TITLE
Can't use async/await with close function

### ISSUE THREAD

**Issue by raaymax** [hemerajs/hemera#186]
It's not a bug. 
More like a feature request.

**Comment by StarpTech** [comment]
Hi @raaymax thanks for checking out hemera. Would you like to send a PR?

**Comment by StarpTech** [comment]
Hi @raaymax I implement it with https://github.com/hemerajs/hemera/pull/187 😄

**Comment by StarpTech** [comment]
Released with 3.4.0

**Comment by raaymax** [comment]
Wow, that was fast :1st_place_medal:  
Thanks!
