### ISSUE TITLE
Export Joi validation to documentation?

### ISSUE THREAD

**Issue by PatrickHeneise** [hemerajs/hemera#192]
Is there a way to generate JSDoc from the Joi definitions? There's plugins for that for fastify/koa/hapi to generate Swagger. Would be very interesting to have that.

How would one approach this issue?

**Comment by StarpTech** [comment]
No, but a plugin is very welcome. You can archive it with the [`onAdd` extension](https://hemerajs.github.io/hemera/docs/extension.html#application-lifecycle)

```js
hemera.ext('onAdd', addDefinition => {
  // some code
  addDefinition.pattern
  addDefinition.schema
  addDefinition.action
  addDefinition.transport
})
```

**Comment by PatrickHeneise** [comment]
great, thanks! We'll look into it

**Comment by StarpTech** [comment]
@PatrickHeneise a very good starting point is https://github.com/fastify/fastify-swagger. You can expose the hemera services with https://github.com/hemerajs/hemera/tree/master/packages/hemera-web

**Comment by PatrickHeneise** [comment]
I wonder if JSDoc would make a better documentation than swagger, after all it is internal documentation. I'll look into it after we're through with the sprint, too many things on the list still, thanks a lot for the starting point!

**Comment by StarpTech** [comment]
Do you using hemera in production or as side-project?

**Comment by PatrickHeneise** [comment]
will be in production soon ;)

**Comment by StarpTech** [comment]
Great, if you have any questions you can contact us on Gitter. Yesterday, we released the new docs https://hemerajs.github.io/hemera/ for hemera 5. Can we add you to the list https://hemerajs.github.io/hemera/users.html ?

**Comment by PatrickHeneise** [comment]
Will do, thanks! Good to know there's new docs. You can assign me to this ticket, so I have it on my tracker.

**Comment by StarpTech** [comment]
I reference the repo here https://github.com/heneise/hemera-joi-jsdoc

**Comment by StarpTech** [comment]
I will close it due to inactivity. Feel free to create a PR to add your plugin to the website.

**Comment by pharophy** [comment]
Any updates?

**Comment by PatrickHeneise** [comment]
Unfortunately not. We had a basic version, but not good enough for a PR.
