### ISSUE TITLE
Hemera inbound/outbound duration

### ISSUE THREAD

**Issue by jeffrichiefs** [hemerajs/hemera#201]
```
Apr 10 15:00:59 orders-service-7898c8c697-hp5jl orders-service     inbound: {
Apr 10 15:00:59 orders-service-7898c8c697-hp5jl orders-service       "id": "257d727bd48c4ff98255400105e0b9fd",
Apr 10 15:00:59 orders-service-7898c8c697-hp5jl orders-service       "duration": "567.88ms",
Apr 10 15:00:59 orders-service-7898c8c697-hp5jl orders-service       "pattern": "cmd:get,id:5,topic:forms"
Apr 10 15:00:59 orders-service-7898c8c697-hp5jl orders-service     } 
```

What does `'duration'` mean?

**Comment by StarpTech** [comment]
Hi @jeffrichiefs `duration` is the time needed for the complete request / reply process.

* Client (Send) -> Server (Reply) -> Client (Received)

**Comment by jeffrichiefs** [comment]
Thanks @StarpTech - how often does Hemera poll the queue? That would be the arrows between the calls.

**Comment by StarpTech** [comment]
@jeffrichiefs which queue? The messages are routed directly through NATS. NATS act as a router.

**Comment by jeffrichiefs** [comment]
By queue I meant NATS - Hemera looks for new messages every so often or am I thinking about this wrong?
