### ISSUE TITLE
Custom logging

### ISSUE THREAD

**Issue by acehko** [hemerajs/hemera#21]
How could I log additional data like `trace$` or `request$`?
The context object is not passed to the logger

**Comment by StarpTech** [comment]
Hi @acehko we seperate internal logging from system events.

If you want to log `request$` or `trace$` you listen on events see [Zipkin](https://github.com/hemerajs/hemera/blob/master/packages/hemera-zipkin/index.js) package as example.

**Comment by acehko** [comment]
@StarpTech Thanks, that's what I was looking for.
I did see these events in the docs: https://github.com/hemerajs/hemera#get-events
But they're a bit different. Looks like the words `Server` and `Client` are missing.

**Comment by StarpTech** [comment]
@acehko yes you're right I updated them some days ago.
