### ISSUE TITLE
Logging id

### ISSUE THREAD

**Issue by danielo515** [hemerajs/hemera#210]
Hello.

One thing i really like about seneca is how it automatically adds a correlation id to every log. Does hemera do the same thing ?

Regards

**Comment by danielo515** [comment]
Hello @StarpTech 
When you have a distributed system like the one this framework and Seneca were made for, you need an unique ID to trace a transaction across systems. What I want is to be able to trace a transaction down the logs by it's ID. For that reason it is needed that a transaction gets an ID when it enters the system and that ID is kept across the entire lifecycle of the transaction as it pass through the different microservices that compose your backend. So, in order to search on the log system (files, graylog, or whatever) for a concrete transaction you need that unique id to be present on all the transaction logs.

I'm not sure if I'm being clear, hope I am.

**Comment by StarpTech** [comment]
Hi @danielo515 we provide a correlation id across calls in hemera. You can use the `trace$.traceId`. You're right this information should be annotated to the logs. Would you like to create a PR?

**Comment by danielo515** [comment]
Sure, it will be a fun way of learning. Should it require a new plugin or modifying an existing one?

**Comment by StarpTech** [comment]
It should be easy to extend. We are using the Pino logger module.

**Comment by danielo515** [comment]
But is it one particular place or should I look for all the calls to the pino logger?

**Comment by StarpTech** [comment]
Hi @danielo515 I think it's not possible without to wrap the default logger interface.
If you want to track the correlation id on each log you have to do:

```js
hemera.log.info({ traceId: this.trace$.traceId, ...props })
```

but we are able to attach the id to all hemera errors [here](https://github.com/hemerajs/hemera/blob/master/packages/hemera/lib/index.js#L391)

**Comment by StarpTech** [comment]
Forget what I said 😄  It possible via [childLogger](https://github.com/pinojs/pino#usage)feature

**Comment by StarpTech** [comment]
Here https://github.com/hemerajs/hemera/pull/211/files check it out 😄

**Comment by danielo515** [comment]
Hello @StarpTech , thanks for your comments.
The provided example seems to be extending the hemera core, is that correct ? Or maybe you are suggesting that this is something each microservice should extend ? I would prefer to have this on the core, even if it is behind a flag.

Do you think that the performance impact of this is one of the reasons why hemera is more performant than Seneca ?

**Comment by StarpTech** [comment]
> The provided example seems to be extending the hemera core, is that correct ? Or maybe you are suggesting that this is something each microservice should extend ? I would prefer to have this on the core, even if it is behind a flag.

Yes, it's correct. In the current implementation, you can set the flag and all logs will contain the tracing data.

> Do you think that the performance impact of this is one of the reasons why hemera is more performant than Seneca?

Definitely not. Hemera was implemented from the ground up to be lightweight, flexible and maintainable. Performance is important but it's not the main aim.

**Comment by StarpTech** [comment]
The feature was released! Thank you for the impulse.
![image](https://user-images.githubusercontent.com/1764424/40515375-da09de4c-5fac-11e8-886a-8cea8906f50e.png)

**Comment by danielo515** [comment]
Awesome ! So it is already available ? How can I activate it ?

**Comment by StarpTech** [comment]
Look at the PR. Option `traceLog:true`

**Comment by StarpTech** [comment]
@danielo515 please upgrade to 5.6.0 I fixed the logging message and added log for the server side as well.
