### ISSUE TITLE
Does hemera.close() killall running jobs?

### ISSUE THREAD

**Issue by jeffrichiefs** [hemerajs/hemera#219]
If Hemera is processing a message and you call hemera.close(), does Hemera finish processing the message or does it ungracefully kill the service?

**Comment by jeffrichiefs** [comment]
A colleague showed me this: https://github.com/hemerajs/hemera/blob/43e0c1c250a44a82a7aa565527c6da9bc8f73224/examples/basic/graceful-shutdown-hemera.js#L15

So I think I have my answer!

💃

**Comment by StarpTech** [comment]
Yes, `hemera.close` will gracefully shutdown.
