### ISSUE TITLE
Adding hemera to Docusaurus users page

### ISSUE THREAD

**Issue by alexperez** [hemerajs/hemera#228]
Hello, Docusaurus would like to add your project to their [Users page](https://docusaurus.io/en/users). Please let me know if that would be okay. More information [here](https://github.com/facebook/Docusaurus/issues/1080).

Thank you.

**Comment by StarpTech** [comment]
Hi @alexperez that would be great! Do you need anything else?

**Comment by alexperez** [comment]
Just permission to use your project logo would be great. Thanks

**Comment by StarpTech** [comment]
Yes, you can use it.
