### ISSUE TITLE
Unable to subscribe to NATS topic when the publisher is not running on Hemera

### ISSUE THREAD

**Issue by Benjaminshafa** [hemerajs/hemera#230]
I have a simple nodejs app that uses the official NATS implementation to publish a topic.
```
var NATS = require('nats');
var nats = NATS.connect();
// // Simple Publisher
 nats.publish('foo', 'Hello World!', function(){
     console.log('msg processed!');
 });
```

Then, I have an app that uses Hemera and tries to subscribe to this topic, but unable to do so.
       
        await hemera.ready();
        hemera.add(
            {
                topic: 'foo'
            },
            function(res) {
                // I am expecting the "res" to have the result...                        
        hemera.act({
            pubsub$: true,
            topic: 'publish_a_new_topic',
            message: "something!"
        })
            }
        );
If I use Hemera.act to publish that topic, then things work fine...

**Comment by StarpTech** [comment]
Hi @Benjaminshafa you can't communicate with NATS driver and Hemera directly. Therefore the interface of the `add` callback is wrong please check the documentation and the examples.
