### ISSUE TITLE
Have you looked into ts-nats?

### ISSUE THREAD

**Issue by orefalo** [hemerajs/hemera#239]
Have you looked into ts-nats?

**Comment by StarpTech** [comment]
Hi @orefalo what's your reason behind that question?

> Have you looked into ts-nats?

Yes

We still rely on `node-nats` because it's solid and we provide our own interface in hemera.

**Comment by orefalo** [comment]
Sorry, my question didn't have much context. Was quickly exploring your project and was wondering why, while it uses ts, it doesn't leverage nats.ts

**Comment by StarpTech** [comment]
Hemera is 100% written in js but we provide typings. Nats-ts was introduced long after node-nats and is relatively new and also the interface has changed completely. For our requirements node-nats is good for now. Thanks for your interest.
