### ISSUE TITLE
[hemera-joi] Validate the whole pattern

### ISSUE THREAD

**Issue by acehko** [hemerajs/hemera#24]
Is it possible to validate the whole pattern using a custom function like in `seneca-joi`?
Example:
```js
seneca.add({
    a: 1,
    joi$: function (schema) {
        return schema.keys({ b: Joi.required() })
    }
})
```

**Comment by StarpTech** [comment]
Hi @acehko yes, you can seperate your data from the pattern and validate it.

```js
seneca.add({
    topic: 'math',
    cmd: 'add',
    data: Joi.object().keys({ b: Joi.required() })
})
```

**Comment by acehko** [comment]
@StarpTech I don't want to separate the data like that. I just want the validation for the whole pattern to be in one "key" in the pattern. Like the `joi$` property in `seneca-joi`. What I want is something like this:
```js
hemera.add({
    topic : 'math',
    cmd : 'add',
    joi$ : function(schema) {
        return schema.keys({
            a : Joi.number().required(),
            b : Joi.number().required()
        });
    }
}
```
The main reason is to be able to separate the validation functions to another module. eg.:
```js
hemera.add({ topic : 'math', cmd : 'add', joi$: require('./validation/add') });
```

**Comment by StarpTech** [comment]
With hemera-joi 0.1.71 you can pass the schema to action by the `joi$` property

```
let Joi = hemera.exposition['hemera-joi'].joi

hemera.add({
    topic : 'math',
    cmd : 'add',
    joi$ : Joi.object().keys({ 
        b: Joi.required()
      })
    }
}
```

**Comment by acehko** [comment]
That was fast, thanks :)
