### ISSUE TITLE
How to reply from middleware or extension?

### ISSUE THREAD

**Issue by faloi** [hemerajs/hemera#240]
I'm trying to return a specific response if params validation fails, but I don't want to throw an error. I tried with all the documented alternatives (`hemera-joi`, middlewares, extensions) but I can't figure how to stop the request and reply.

My "middleware" logic would be something like this:

```js
async function validateParamsAndRun(schema, req, callback) {
  const { error, value } = schema.validate(req.params || {});

  if (error) {
    return { error: true, message: {error: error.message}, status: 422 };
  } else {
    return { error: false, message: await callback(value), status: 200 };
  }
}
```

**Comment by StarpTech** [comment]
Hi @faloi I don't understand your example. Could you provide a complete example in https://repl.it/@StarpTech/Hemera-7?

**Comment by faloi** [comment]
Something like this: https://repl.it/repls/CharmingGoldenrodSpreadsheets

In short: I want to reply _earlier_ from a middleware (or perhaps an extension), without executing the handler function.

**Comment by StarpTech** [comment]
Hi @faloi this can be archived by `reply.send(val)` https://repl.it/repls/FancyFriendlyOs

**Comment by faloi** [comment]
Great. This can be achieved in any method that receives the `reply` parameter? 

I'll add it to the docs and send you a PR. :smile:

**Comment by StarpTech** [comment]
> Great. This can be achieved in any method that receives the reply parameter?

Yes, I always recommend to read the tests. 

> I'll add it to the docs and send you a PR. smile

That would be graet :smile:
