### ISSUE TITLE
hemera-zipkin package missing

### ISSUE THREAD

**Issue by veeramarni** [hemerajs/hemera#248]
In version v7.0.0 we don't see `hemera-zipkin` package, can you please add it.

**Comment by StarpTech** [comment]
Hi @veeramarni the package was removed because we didn't maintain it anymore. It should be still on the registry. Feel free to fork it.

**Comment by veeramarni** [comment]
@StarpTech Can i send PR for it?

**Comment by StarpTech** [comment]
@veeramarni we have no use for that package. You can maintain it.
