### ISSUE TITLE
Adding A MongoDB Database Adapter

### ISSUE THREAD

**Issue by Linicks** [hemerajs/hemera#31]
What's the interest level of adding a Mongodb Database Adapter?

**Comment by StarpTech** [comment]
Hi @Linicks mongodb is great. PR is welcome :) 
Please ensure that your Interface is compatible with the store Interface. 

https://github.com/hemerajs/hemera/tree/master/packages/hemera-store as an example see `arango-store` thank you.

**Comment by StarpTech** [comment]
I close it because its no issue. If you have any ideas for future plugins come in gitter :)
