### ISSUE TITLE
Typescript typings

### ISSUE THREAD

**Issue by pocesar** [hemerajs/hemera#45]
Does hemera plans to have typescript typings? It's great for new comers to this lib and to ensure proper code structure with self documenting typings

**Comment by StarpTech** [comment]
PR are welcome :)  At the moment its not planned.

**Comment by pocesar** [comment]
I plan to refactor my Express microservices using Hemera, so I guess it will be a hands-on typings as I refactor, and I can send the PR

**Comment by StarpTech** [comment]
@pocesar that would be great

**Comment by StarpTech** [comment]
What's the status?

**Comment by StarpTech** [comment]
I add first draft of typescript defintion.  https://github.com/hemerajs/hemera/blob/master/packages/hemera/lib/index.d.ts

**Comment by pocesar** [comment]
@StarpTech usually the typings are done side-by-side, I have the initial "any" typings as well, but that only helps with understanding the overall API, doesn't really help with the typings. To generate the typings side-by-side, you must use TSC on the .js files renamed to .ts, and permissive settings in tsconfig.json. but since Hemera is considered to be 'unstable' (API wise) it might be hard to keep track manually of the changes, but I'll try my best

**Comment by StarpTech** [comment]
Hi @pocesar what do you mean "the api is considered unstable"? The core api is stable. I don't want to transpile the code because I can't see any benefits except intelli sense. I think creating definition files can help some people to get start with hemera.

**Comment by StarpTech** [comment]
If you create a branch I can help you. Thanks.

**Comment by pocesar** [comment]
well, per definition, semver considers anything below 1.0.0 to be unstable. and the many changes in the files make it hard to keep track and update the typings accordingly

**Comment by StarpTech** [comment]
@pocesar Hemera 1.0.0 was released, it was long overdue.

**Comment by StarpTech** [comment]
Hi @pocesar still interesting in complete ts files?

**Comment by sittingbool** [comment]
Hey, I am also using typescript with hemera and really would appreciate the effort...

**Comment by StarpTech** [comment]
Hi @sittingbool great news I released new definition file with the latest release.

**Comment by StarpTech** [comment]
But if you upgrade to 1.5 there are some breaking changes but with minimal effort.

**Comment by sittingbool** [comment]
great, i will check that out! many thanks!

**Comment by sittingbool** [comment]
Hmm, I checked this on the example project from the getting started tut. But TypeScript gives me errors already because all the definitions in the interface Config are mandatory. Are they really? Otherwise a simple ? at the before the ; would be nice ;). I can help you with that. Also a module declaration would be nice to have a standard import mechanism.

**Comment by StarpTech** [comment]
Hi @sittingbool I don't use typescript but want to provide for the users. The definition file is not perfect. Would be great if you could create a PR. Not fields are mandatory. The default values you can take from `configScheme.js`

**Comment by StarpTech** [comment]
@sittingbool are you working on this?

**Comment by sittingbool** [comment]
yes, unfortunately nats has a faulty type-definition-file as well. also testing everything is not that easy.  but i can create a pull request in the next days covering the basic usage. i hope the nats module owner will accept my changes also.

**Comment by StarpTech** [comment]
Can I close it @sittingbool  ?

**Comment by StarpTech** [comment]
Will close the issue hemera has typescript support.
