### ISSUE TITLE
running within docker

### ISSUE THREAD

**Issue by pocesar** [hemerajs/hemera#47]
Is there any limitation for running hemera microservices inside Docker? if so, what should be done as workarounds?

**Comment by StarpTech** [comment]
Hi @pocesar it perfectly fits see https://github.com/hemerajs/aither. Its an example setup with docker-compose

**Comment by pocesar** [comment]
very nice, should mention this on readme :) (I got here through Node.js Weekly)

**Comment by StarpTech** [comment]
Cool, I just saw it too in Node.js Weekly. I updated the docs. Thank you.
