### ISSUE TITLE
Support queues & workers

### ISSUE THREAD

**Issue by gregory** [hemerajs/hemera#55]
It seems like NATS support [message queueing pattern](http://nats.io/documentation/concepts/nats-queueing/)
Unless i missed something, that seems to be missing. Any plan to implement it?

**Comment by StarpTech** [comment]
Hi @gregory hemera support it by default. Every RPC call use a "queue group name" this ensure that all one-tone traffic is load balanced. https://hemerajs.github.io/hemera/1_request_reply.html Thanks for the hint. I improved the documentation.
