### ISSUE TITLE
couldn't support other languages?

### ISSUE THREAD

**Issue by arden** [hemerajs/hemera#71]
couldn't support other languages?

**Comment by StarpTech** [comment]
HI @arden the toolkit is only for nodejs but NATS is available for many other programming languages. You can communicate with other clients but only with the basic funtionality of the NATS driver. See https://github.com/hemerajs/hemera/blob/master/examples/nats-only.js

**Comment by BransonGitomeh** [comment]
https://github.com/hemerajs/hemera/blob/master/examples/nats-only.js link is broken :-)

**Comment by StarpTech** [comment]
https://github.com/hemerajs/hemera/blob/master/examples/basic/nats-only.js
