### ISSUE TITLE
hermera can't support Promise or Async/Await?

### ISSUE THREAD

**Issue by arden** [hemerajs/hemera#73]
hermera can't support Promise or Async/Await?

**Comment by StarpTech** [comment]
Currently there is no support for that.  There is an example how to execute many acts in parallel or how to compose them with the `async` package. 

Promisyfing the functions aren't enough it would break the error handling.

**Comment by StarpTech** [comment]
Look at https://github.com/hemerajs/hemera/blob/master/examples/async.js

**Comment by StarpTech** [comment]
Hi @arden look at PR https://github.com/hemerajs/hemera/pull/76/files#diff-a8e5aaaaec2bc334c0cc45aeae2d52ad I implemented support for generators and promises.

**Comment by zhaoyao91** [comment]
+1 look forward to support of async/await

**Comment by StarpTech** [comment]
Async / Await is only supported by nodejs 7 with the current solution we don't have to transpile anything. We supporting generators with the Co package it behaves almost the same as async / await.
