### ISSUE TITLE
Add Joi option for payload validation

### ISSUE THREAD

**Issue by tribou** [hemerajs/hemera#8]
It would be nice if I could switch parambulator for [Joi validation](https://github.com/hapijs/joi) for the in/out payload validation.

**Comment by StarpTech** [comment]
Hi @tribou see https://github.com/hemerajs/hemera/pull/10 if you have any question or improvements dont hestitate :)

**Comment by StarpTech** [comment]
For example
https://github.com/hemerajs/hemera/blob/master/examples/custom-payload-validator.js
