### ISSUE TITLE
Benchmarks

### ISSUE THREAD

**Issue by expelledboy** [hemerajs/hemera#83]
Hi Dustin

Have been following your project, and evaluating all alternatives for a project I am about to rewrite. Have you seen the results posted at https://github.com/icebob/microservices-benchmark?

Do you feel its a fair comparison?

Also I see you have files to do benchmarks, how do I run them?

**Comment by StarpTech** [comment]
Hi @expelledboy thanks for the information I didn't notice that. Please follow the contribution guide https://github.com/hemerajs/hemera/blob/master/CONTRIBUTING.md don't forget to install and run NATS.  After that you can run it as any other node script.

**Comment by StarpTech** [comment]
> Do you feel its a fair comparison?

Hemera has not been designed for high performance. It choose simplicity and reliability as primary goals. It has been designed to create lots of microservices which act together as central nervous system. Transport independency was not considered to be a relevant factor. Therefore we use pattern matching which is very powerful. The fact that Hemera needs a broker is an argument which should be taken into consideration when you compare the system. The comparison would be much more meaningful when the test would respect the nature of a microservice environment therefore distributed on different machines or at least on multiple processes. The relevant difference between microservice frameworks like senecajs, molecure is not the performance its about the complexity you need to manage. Hemera client is still a subscriber of NATS with some magic in routing and extensions. We don't have to worry about all different aspects in a distributed system like routing, load-balance, service-discovery .. but I really welcome the different implementations for NodeJs we can learn a lot from each other (tracing, error handling ...)

**Comment by StarpTech** [comment]
I never released official benchmark but to get a better impression you can run the included benchmark. My test on i5-6600K CPU @ 3.50GHz 3.50 GHz

Publish: ~ 53474 msgs/sec
Request: ~ 33624 msgs/sec
Request-responses: ~ 12285 /sec
Subscriber: ~ 51493 msgs/sec

which includes by default a packet size of ~ 27 bytes without payload

**Comment by StarpTech** [comment]
If you have any questions join the gitter channel. Thanka.
