### ISSUE TITLE
hemera-web can support custom the route url?

### ISSUE THREAD

**Issue by arden** [hemerajs/hemera#84]
hemera-web can support custom the route url?
http://localhost:3000/?topic=math&cmd=add&a=10&b=10
like as
http://localhost:3000/math/cmd/?a=10&b=10

**Comment by StarpTech** [comment]
Hi @arden hemera-web works with query and payload to identify the pattern. `http://localhost:3000/math/cmd` is the url but we can implement a pattern to support e.g `/math/cmd/add` feel free to create PR its should be trivial.

**Comment by StarpTech** [comment]
@arden after the rewrite of `hemera-web` we have support for url params. `http://localhost:3000/math/add?a=1&b=2`
