### ISSUE TITLE
hemera-web node version requirement

### ISSUE THREAD

**Issue by soundstep** [hemerajs/hemera#98]
## Description
I need a really high version of node to be able to use hemera-web.
hemera-web starts to wok with node 7.6.0
Before that I get an error.

## Steps to Reproduce
1. npm install -g n
2. n 7.5.0
3. execute hemera-web example:
```const Hemera = require('nats-hemera')
const nats = require('nats').connect()
const hemeraWeb = require('hemera-web')
 
const hemera = new Hemera(nats)
hemera.use(hemeraWeb, {
  port: 3000,
  host: '127.0.0.1',
  pattern: {} // default pattern 
})
 
hemera.ready(() => {
  hemera.add({
    topic: 'math',
    cmd: 'add'
  }, (req, cb) => {
    cb(null, req.a + req.b)
  })
})
```

## Expected Result
Having the nodejs script executing

## Actual Result
Get an error with the async keyword (I think):
```
╰─$ node -v
v6.5.0
╭─romuald@C02M2HBKFD57 ~/Documents/devserver/workspace/hemera-playground/microservices-example ‹2.2.5›
╰─$ node products/index.js
/Users/romuald/Documents/devserver/workspace/hemera-playground/microservices-example/node_modules/hemera-web/lib/index.js:35
    this._server = Micro(async (req, res) => {
                               ^
SyntaxError: Unexpected token (
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:528:28)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/romuald/Documents/devserver/workspace/hemera-playground/microservices-example/node_modules/hemera-web/index.js:3:13)
    at Module._compile (module.js:556:32)
```
## Context

- [x] nats-hemera (core)
- [x] hemera-web

## Your Environment
- NATS: 0.9.6
- Hemera: 1.3.2
- NodeJs: 7.5.0
- Environment name and version:
- Operating System and version: OSX 10.10.5

**Comment by StarpTech** [comment]
Hi @soundstep good news. Hemera-web was rewritten with express 4 to support Node > 4. The code was also simplified. Look at https://github.com/hemerajs/hemera/commit/bb9abcf9df3ea7aaabe40b585f4c6f2220273611. Thanks for reporting.

Published with
- hemera-web@0.0.18
