### ISSUE TITLE
node version issue with henera-store (npm error)

### ISSUE THREAD

**Issue by soundstep** [hemerajs/hemera#99]
## Description
Using nodejs 7.6.0, I got an NPM error when installing

## Steps to Reproduce
1. npm install -g n
2. n 7.6.0
3. npm install hemera-store

## Expected Result
Being able to install hemera-store

## Actual Result
NPM error:
```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'install',
1 verbose cli   'hemera-store' ]
2 info using npm@4.1.2
3 info using node@v7.6.0
4 verbose stack Error: Cannot find module 'internal/fs'
4 verbose stack     at Function.Module._resolveFilename (module.js:470:15)
4 verbose stack     at Function.Module._load (module.js:418:25)
4 verbose stack     at Module.require (module.js:498:17)
4 verbose stack     at require (internal/module.js:20:19)
4 verbose stack     at evalmachine.<anonymous>:18:20
4 verbose stack     at Object.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/cmd-shim/node_modules/graceful-fs/fs.js:11:1)
4 verbose stack     at Module._compile (module.js:571:32)
4 verbose stack     at Object.Module._extensions..js (module.js:580:10)
4 verbose stack     at Module.load (module.js:488:32)
4 verbose stack     at tryModuleLoad (module.js:447:12)
5 verbose cwd /Users/romuald/Documents/devserver/workspace/hemera-playground/microservices-example
6 error Darwin 14.5.0
7 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "hemera-store"
8 error node v7.6.0
9 error npm  v4.1.2
10 error code MODULE_NOT_FOUND
11 error Cannot find module 'internal/fs'
12 error If you need help, you may report this error at:
12 error     <https://github.com/npm/npm/issues>
13 verbose exit [ 1, true ]
```

## Context

- [x] nats-hemera (core)
- [ ] hemera-zipkin
- [x] hemera-store
- [ ] hemera-stats
- [ ] hemera-rabbitmq
- [ ] hemera-nsq
- [ ] hemera-arango-store
- [ ] hemera-sql-store
- [ ] hemera-elasticsearch
- [ ] hemera-couchbase-store
- [ ] hemera-mongo-store
- [ ] hemera-joi
- [ ] hemera-parambulator
- [ ] hemera-msgpack
- [ ] hemera-avro
- [ ] hemera-redis-cache
- [ ] hemera-jwt-auth

## Your Environment
- NATS: 0.9.6
- Hemera: 1.3.2
- NodeJs: 7.6.0
- Environment name and version:
- Operating System and version: OSX 10.10.5

**Comment by soundstep** [comment]
I found some info there that seems to be related:
https://github.com/nodejs/node/issues/9355
I fixed the problem by removing all global npm modules and re-installing node.
Not sure how this is related to this module, as it never happened before. I don't seem to have this problem with other modules.
Hope that helps.

**Comment by StarpTech** [comment]
Thanks for research. I also never saw this issue. Its definitly no related to hemera.
